name: CI/CD for Angular Project

# Ausführung bei allen Push- und Pull-Request in dem Main-Branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./programmierprojekt


jobs:
  build:
    name: Build and Test Angular App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install Dependencies
      - name: Install Dependencies
        run: npm install -g @angular/cli@18

      # Stage: Linting
      - name: Install ESLint
        run: ng add @angular-eslint/schematics --skip-confirmation
      - name: Run Linter
        run:  ng lint

      # Stage: SCA
      - name: Install Snyk
        run: npm install -g snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Test configuration
        run: snyk test
      - name: Code analysis
        run: snyk code test
      - name: Transfer results
        run: snyk monitor
        
      # Stage: Test-Headless
      - name: Run Headless Test in Chrome
        run: ng test --watch=false --browsers=ChromeHeadless
